function createfigure(XMatrix1, YMatrix1, ZMatrix1,size_x,size_y)
%CREATEFIGURE(XMatrix1, YMatrix1, ZMatrix1)
%  XMATRIX1:  matrix of x data
%  YMATRIX1:  matrix of y data
%  ZMATRIX1:  matrix of z data

%  Auto-generated by MATLAB on 12-Nov-2019 09:31:48

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot3
plot31 = plot3(XMatrix1,YMatrix1,ZMatrix1,'LineStyle','none');
set(plot31(1),'DisplayName','Predicted','Marker','o','Color',[0 1 0]);
set(plot31(2),'DisplayName','Ground truth','Marker','*','Color',[1 0 0]);

% Create zlabel
zlabel('(mm)');

% Create ylabel
ylabel('(mm)');

% Create xlabel
xlabel('(mm)');
axis off;

view(axes1,[-89.9372004796931 -90]);
axis(axes1,'tight');
xlim(size_x);
ylim(size_y);
% xlim([0 1.8]);% xlim([0.6 1.7]);%xlim([-1.6 -0.05]);
% ylim([-0.3 0.3]);% ylim([-1.2 -0.35]);%ylim([-0.8 0.5]);
% xlim([-2.9 8.3]);%xlim([-2.9 6.8]);
% ylim([-5.6 17.3]);
% Set the remaining axes properties
set(axes1,'DataAspectRatio',[1 1 1]);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.221985115336144 0.128367344436423 0.161479595937813 0.0341836759717402],...
    'fontsize',35);

